### ISSUE TITLE
Factor encoding with missing data.

### ISSUE THREAD

**Issue by legaultmarc** [pgxcentre/genetest#1]
Factors are encoded by the modelspec before the final data matrix has been fully generated. Because of this, it is possible that when NA values are dropped some factor levels disappear completely.

To account for this, analysis could do an extra step drop irrelevant columns. An easy fix would be to drop columns that sum to zero ( @lemieuxl ).

**Comment by lemieuxl** [comment]
We need to make sure that this extra step is performed **only on factor columns**. Other (numerical) columns can sum to zero (e.g. values between -1 and +1).
