### ISSUE TITLE
Allele mixup causes a test to not pass

### ISSUE THREAD

**Issue by legaultmarc** [pgxcentre/genetest#4]
See commit b2da267

We should discuss this @lemieuxl 

The two options is to change the test data or to add a flag in MarkerInfo to indicate that the alleles have not been validated using the actual genotypes. Maybe something like "minor_allele_validated=False".

**Comment by legaultmarc** [comment]
Since afcb4f7b62d746b787f546496af05f1cc813155d, instead of 'minor' and 'major', the MarkerInfo class has 'a1' and 'a2'. A third field, 'minor', is used to point to one or the other as being the minor allele. This is done using the class constants ``MarkerInfo.A1`` or ``MarkerInfo.A2``.

The only thing left to do is to validate the allele encoding in the failing test and to fix it.

**Comment by lemieuxl** [comment]
The allele encoding was checked and modified in the test (commit af52f0b).
