### ISSUE TITLE
Use 'cyvcf2' instead of 'pysam'

### ISSUE THREAD

**Issue by lemieuxl** [pgxcentre/genetest#6]
We should use [`cyvcf2`](https://github.com/brentp/cyvcf2) instead of `pysam` for VCF parsing. According to this [paper](https://doi.org/10.1093/bioinformatics/btx057), it is 6.89 times faster than `pysam`.

**Comment by legaultmarc** [comment]
That's not genetest's job anymore. Should be moved to geneparse.
