### ISSUE TITLE
Behaviour with RuntimeWarning in GWAS

### ISSUE THREAD

**Issue by legaultmarc** [pgxcentre/genetest#8]
I "continue" when a RuntimeWarning is encountered because sometimes "results" was undefined and it crashed the loop.

I think the code was originally meant to not behave like this, so I think you should verify that I didn't break anything.

https://github.com/pgxcentre/genetest/blob/6c9a10bf230667415962094bf871c15fb176edb5/genetest/analysis.py#L137

**Comment by lemieuxl** [comment]
I thought that `RuntimeWarning` meant that a result was still generated. Here is an example of what can happen.
The `RuntimeWarning` appears at [line 43 of the linear model](https://github.com/pgxcentre/genetest/blob/b69883ab920b9748f88ed9d60bfeda25caf79581/genetest/statistics/models/linear.py#L43).
